### ISSUE TITLE
start-up - unable to register with Registry in allotted time

### ISSUE THREAD

**Issue by AlanTuring1988** [edgexfoundry/device-rest-go#29]
Hi, 
I have any problem during the start-up of the device-rest-go container.
From log I see this error message:

'...
level=WARN ts=2020-06-23T10:35:15.938223937Z app=my-device-rest source=registry.go:139 msg="registry is not available"
level=ERROR ts=2020-06-23T10:35:16.940357124Z app=my-device-rest source=bootstrap.go:43 msg="unable to register with Registry in allotted time"
...'

I used my docker-compose.yaml file with consul:1.3.1 and I added this microservice as the follow example. is it correct? Is there an example of the docker-compose that I can compare? is it necessary to set the volume attribute? if yes, How I can set it?

"...
device-rest:
   image: edgexfoundry/docker-device-rest-go:0.0.0-dev
   ports:
     - "49986:49986"
   container_name: my-device-rest
   hostname: my-device-rest
   networks:
     - my-network
   volumes:
     - ???
   depends_on:
     - data
     - metadata
...."

Thanks and BR.

**Comment by lenny-intel** [comment]
@AlanTuring1988 , please use one of the Geneva compose files here.
https://github.com/edgexfoundry/developer-scripts/tree/master/releases/geneva/compose-files
Note that Mongo has been deprecated for EdgeX, so recommend sticking with a Redis version of the compose files.

**Comment by AlanTuring1988** [comment]
Thanks lenny. it was what I was looking for.
BR.
